name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install NASM
      run: sudo apt-get install nasm
    
    - name: Install GCC
      run: sudo apt-get install gcc && sudo apt-get install gcc-multilib
  
    - name: Build
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
